from pathlib import Path
import logging
import shutil
import subprocess


def check_ffmpeg() -> str:
    executable = shutil.which('ffmpeg')
    if not executable:
        try:
            import imageio_ffmpeg
            executable = imageio_ffmpeg.get_ffmpeg_exe()
        except (ImportError, RuntimeError):
            raise ValueError('FFmpeg not found. Please install FFmpeg and add it to PATH.') from None
    result = subprocess.run([executable, '-version'], capture_output=True, timeout=20)
    if result.returncode:
        raise ValueError('FFmpeg cannot run. Please check your installation.')
    return executable


def merge_clips(events: list[dict], duration: float, pre: float, post: float, gap: float,
                windows: dict | None = None, overrides: dict | None = None) -> list[dict]:
    windows, overrides = windows or {}, overrides or {}
    if any(index > len(events) for index in overrides):
        raise ValueError('Override event number exceeds the number of events in this video')
    ranges = []
    for index, event in enumerate(events):
        window = windows.get(event.get('kind', 'kill'), {'pre': pre, 'post': post})
        start, end = max(0, event['time']-window['pre']), min(duration, event['time']+window['post'])
        override = overrides.get(index+1, {})
        start, end = override.get('start', start), override.get('end', end)
        if override and not (0 <= start <= event['time'] <= end <= duration and start < end):
            raise ValueError(f'Event {index+1}: range must contain the event, stay within the video and have start < end')
        if end > start:
            ranges.append({'start': start, 'end': end, 'event_indices': [index]})
    # A long lead-in may begin before an earlier event's clip: sort ranges by
    # their start before merging, otherwise the earlier footage can be lost.
    clips: list[dict] = []
    for clip in sorted(ranges, key=lambda item: item['start']):
        start, end = clip['start'], clip['end']
        if clips and start - clips[-1]['end'] <= gap:
            clips[-1]['end'] = max(end, clips[-1]['end'])
            clips[-1]['event_indices'] = sorted(clips[-1]['event_indices'] + clip['event_indices'], key=lambda i: events[i]['time'])
        else:
            clips.append(clip)
    return clips


def combine_clips(exports: list[dict], output: Path, executable: str) -> None:
    """Join chronological exported clips; all are produced from one source."""
    if not exports:
        return
    playlist = output.with_suffix('.concat.txt')
    temporary = output.with_name(output.stem + '.partial.mp4')
    # Names are generated by cut_clips and contain no user-provided quoting.
    playlist.write_text(''.join(f"file '{Path(clip['path']).name}'\n" for clip in exports), encoding='utf-8')
    try:
        result = subprocess.run([executable, '-hide_banner', '-nostdin', '-y', '-f', 'concat', '-safe', '0',
                                 '-i', str(playlist), '-c', 'copy', '-movflags', '+faststart', str(temporary)], capture_output=True)
        if result.returncode or not temporary.is_file() or not temporary.stat().st_size:
            raise ValueError('FFmpeg concatenation failed: ' + result.stderr.decode('utf-8', errors='replace')[-2000:])
        temporary.replace(output)
    finally:
        playlist.unlink(missing_ok=True)
        temporary.unlink(missing_ok=True)


def ffmpeg_command(executable: str, video: Path, output: Path, clip: dict, codec: str) -> list[str]:
    command = [executable, '-hide_banner', '-nostdin', '-y', '-ss', f'{clip["start"]:.6f}',
               '-i', str(video), '-t', f'{clip["end"]-clip["start"]:.6f}',
               '-map', '0:v:0', '-map', '0:a:0?']
    if codec == 'copy':
        command += ['-c', 'copy']
    else:
        command += ['-c:v', codec, '-c:a', 'aac']
        command += ['-preset', 'fast', '-crf', '20'] if codec == 'libx264' else ['-preset', 'p4', '-cq', '20']
    return command + ['-movflags', '+faststart', str(output)]


def cut_clips(video: Path, output_dir: Path, clips: list[dict], mode: str, executable: str,
              names: list[str] | None = None) -> list[dict]:
    if names is not None and (len(names) != len(clips) or len(set(names)) != len(names)
            or any(Path(name).name != name or '/' in name or '\\' in name or "'" in name
                   or Path(name).suffix.lower() != '.mp4' for name in names)):
        raise ValueError('Clip names must be unique MP4 filenames without path separators or quotes')
    output_dir.mkdir(parents=True, exist_ok=True)
    codec = 'copy' if mode == 'fast' else 'h264_nvenc'
    results = []
    for index, clip in enumerate(clips, 1):
        suffix = '_multi' if len(clip['event_indices']) > 1 else ''
        output = output_dir / (names[index-1] if names is not None else f'kill_{index:03}{suffix}.mp4')
        temporary = output.with_name(output.stem + '.partial.mp4')
        logging.info('Cutting %s: %.3f–%.3f', output.name, clip['start'], clip['end'])
        try:
            result = subprocess.run(ffmpeg_command(executable, video, temporary, clip, codec), capture_output=True)
            if result.returncode and codec == 'h264_nvenc':
                logging.warning('NVENC failed; retrying with libx264. %s', result.stderr.decode('utf-8', errors='replace')[-2000:])
                codec = 'libx264'
                result = subprocess.run(ffmpeg_command(executable, video, temporary, clip, codec), capture_output=True)
            if result.returncode or not temporary.is_file() or temporary.stat().st_size == 0:
                raise ValueError(f'FFmpeg failed for {video.name}: {result.stderr.decode("utf-8", errors="replace")[-3000:]}')
            temporary.replace(output)
            results.append({**clip, 'path': str(output), 'codec': codec})
        finally:
            temporary.unlink(missing_ok=True)
    return results
